<Container>:
    display: display
    rows: 5
    BoxLayout:
        orientation: "vertical"
        PgcdButton:
            on_release: root.pgcd()
		PpcmButton:
			on_release : root.ppcm()
		PremierButton:
			on_release : root.premier()
		FacteurButton:
			on_release : root.facteurs()
        LeaveButton:
            on_release: root.leave()
    Label:
        id: display
        font_size: dp(50)
        text: '0'
		